DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(63) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(63) UNIQUE,
    is_valid BOOLEAN DEFAULT FALSE,
    is_notified BOOLEAN DEFAULT TRUE
);

DROP TABLE IF EXISTS POST;
CREATE TABLE POST (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    image_name VARCHAR(255) NOT NULL, 
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS HEART;
CREATE TABLE HEART (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES POST(id) ON DELETE CASCADE,
    UNIQUE (user_id, post_id)
);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES POST(id) ON DELETE CASCADE
);